version: '3'
services:
  httpd:
    image: tigerwill90/7.2.15-apache:latest
    container_name: httpd
    ports:
      - 80:80
    restart: always
    volumes:
      - ./src:/var/www/html
      - ./logs/apache2:/var/log/apache2
    networks:
      - api
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      - api
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
    networks:
      - api
networks:
  api:
    driver: bridge