-- MySQL Script generated by MySQL Workbench
-- Sat Dec  1 16:53:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema independents
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `independents` ;

-- -----------------------------------------------------
-- Schema independents
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `independents` DEFAULT CHARACTER SET utf8 ;
USE `independents` ;

-- -----------------------------------------------------
-- Table `independents`.`offices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `independents`.`offices` ;

CREATE TABLE IF NOT EXISTS `independents`.`offices` (
                                                      `offices_id` INT NOT NULL AUTO_INCREMENT,
                                                      `offices_adress` VARCHAR(80) NULL,
  `offices_npa` VARCHAR(10) NULL,
  `offices_city` VARCHAR(45) NULL,
  `offices_cp` VARCHAR(10) NULL,
  `offices_name` VARCHAR(45) NULL,
  `offices_phone` VARCHAR(45) NULL,
  `offices_fax` VARCHAR(45) NULL,
  `offices_email` VARCHAR(250) NULL,
  `offices_description` VARCHAR(250) NULL,
  `offices_district` VARCHAR(45) NULL,
  `offices_type` VARCHAR(45) NULL,
  `offices_independents` TINYINT NOT NULL,
  PRIMARY KEY (`offices_id`),
  UNIQUE INDEX `offices_phone_UNIQUE` (`offices_phone` ASC),
  UNIQUE INDEX `offices_fax_UNIQUE` (`offices_fax` ASC),
  UNIQUE INDEX `offices_email_UNIQUE` (`offices_email` ASC))
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `independents`.`therapists`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `independents`.`therapists` ;

CREATE TABLE IF NOT EXISTS `independents`.`therapists` (
                                                         `therapists_id` INT NOT NULL AUTO_INCREMENT,
                                                         `therapists_firstname` VARCHAR(80) NOT NULL,
  `therapists_lastname` VARCHAR(80) NOT NULL,
  `therapists_offices_id` INT NULL,
  `therapists_title` VARCHAR(10) NOT NULL,
  `therapists_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`therapists_id`, `therapists_offices_id`),
  INDEX `fk_therapists_offices1_idx` (`therapists_offices_id` ASC),
  CONSTRAINT `fk_therapists_offices1`
  FOREIGN KEY (`therapists_offices_id`)
  REFERENCES `independents`.`offices` (`offices_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `independents`.`phones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `independents`.`phones` ;

CREATE TABLE IF NOT EXISTS `independents`.`phones` (
                                                     `phones_id` INT NOT NULL AUTO_INCREMENT,
                                                     `phones_type` VARCHAR(25) NOT NULL,
  `phones_numero` VARCHAR(45) NOT NULL,
  `phones_therapists_id` INT NOT NULL,
  PRIMARY KEY (`phones_id`, `phones_therapists_id`),
  INDEX `fk_phones_therapist_idx` (`phones_therapists_id` ASC),
  CONSTRAINT `fk_phones_therapist`
  FOREIGN KEY (`phones_therapists_id`)
  REFERENCES `independents`.`therapists` (`therapists_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
  ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `independents`.`emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `independents`.`emails` ;

CREATE TABLE IF NOT EXISTS `independents`.`emails` (
                                                     `emails_id` INT NOT NULL AUTO_INCREMENT,
                                                     `emails_adress` VARCHAR(250) NOT NULL,
  `emails_therapists_id` INT NOT NULL,
  PRIMARY KEY (`emails_id`, `emails_therapists_id`),
  UNIQUE INDEX `email_adress_UNIQUE` (`emails_adress` ASC),
  INDEX `fk_emails_therapists1_idx` (`emails_therapists_id` ASC),
  CONSTRAINT `fk_emails_therapists1`
  FOREIGN KEY (`emails_therapists_id`)
  REFERENCES `independents`.`therapists` (`therapists_id`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
  ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `independents`.`offices`
-- -----------------------------------------------------
START TRANSACTION;
USE `independents`;
INSERT INTO `independents`.`offices` (`offices_id`, `offices_adress`, `offices_npa`, `offices_city`, `offices_cp`, `offices_name`, `offices_phone`, `offices_fax`, `offices_email`, `offices_description`, `offices_district`, `offices_type`, `offices_independents`) VALUES (1, 'Avenue des Morgines 39', '1213', 'Genève', NULL, 'A 2 mains', '0227937300', NULL, NULL, NULL, NULL, 'Pédiatrie', 0);
INSERT INTO `independents`.`offices` (`offices_id`, `offices_adress`, `offices_npa`, `offices_city`, `offices_cp`, `offices_name`, `offices_phone`, `offices_fax`, `offices_email`, `offices_description`, `offices_district`, `offices_type`, `offices_independents`) VALUES (2, 'Bois de la Chappelle 105', '1213', 'Onex', '68', NULL, NULL, NULL, NULL, NULL, NULL, 'Pédiatrie', 1);

COMMIT;


-- -----------------------------------------------------
-- Data for table `independents`.`therapists`
-- -----------------------------------------------------
START TRANSACTION;
USE `independents`;
INSERT INTO `independents`.`therapists` (`therapists_id`, `therapists_firstname`, `therapists_lastname`, `therapists_offices_id`, `therapists_title`, `therapists_type`) VALUES (1, 'Catherine', 'DEPALLENS', 1, 'Mme', 'Pédiatrie');
INSERT INTO `independents`.`therapists` (`therapists_id`, `therapists_firstname`, `therapists_lastname`, `therapists_offices_id`, `therapists_title`, `therapists_type`) VALUES (2, 'Corinne', 'MASSON FRIEDLI', 1, 'Mme', 'Pédiatrie');
INSERT INTO `independents`.`therapists` (`therapists_id`, `therapists_firstname`, `therapists_lastname`, `therapists_offices_id`, `therapists_title`, `therapists_type`) VALUES (3, 'Ivo', 'CANONICA', 1, 'M', 'Pédiatrie');
INSERT INTO `independents`.`therapists` (`therapists_id`, `therapists_firstname`, `therapists_lastname`, `therapists_offices_id`, `therapists_title`, `therapists_type`) VALUES (4, 'Christelle', 'ABRIEL', 2, 'Mme', 'Pédiatrie');

COMMIT;


-- -----------------------------------------------------
-- Data for table `independents`.`phones`
-- -----------------------------------------------------
START TRANSACTION;
USE `independents`;
INSERT INTO `independents`.`phones` (`phones_id`, `phones_type`, `phones_numero`, `phones_therapists_id`) VALUES (1, 'tel', '0796522831', 3);
INSERT INTO `independents`.`phones` (`phones_id`, `phones_type`, `phones_numero`, `phones_therapists_id`) VALUES (2, 'tel/fax', '0227928968', 4);

COMMIT;

